# version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=300
      - SE_SESSION_RETRY_INTERVAL=5
      - SE_GRID_MAX_SESSION=24  # Reduced from default
      - TZ=America/New_York # Set to your timezone
    platform: linux/amd64


  chrome-node-1:
    image: selenium/node-chrome:4.10.0
    container_name: chrome-node-1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4  # browser maximum sessions per node
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true  # Allow overriding default max sessions
      - SE_NODE_SESSION_TIMEOUT=300 # add session timeout
      - TZ=America/New_York # Set to your timezone
    # ports:
      # - "5900:5900"  # For VNC access if needed
    shm_size: "2g" # Increase shared memory for Chrome
    platform: linux/amd64


  chrome-node-2:
    image: selenium/node-chrome:4.10.0
    container_name: chrome-node-2
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
      - TZ=America/New_York
    shm_size: "2g"
    platform: linux/amd64


  chrome-node-3:
    image: selenium/node-chrome:4.10.0
    container_name: chrome-node-3
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
      - TZ=America/New_York
    shm_size: "2g"
    platform: linux/amd64


  chrome-node-4:
    image: selenium/node-chrome:4.10.0
    container_name: chrome-node-4
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
      - TZ=America/New_York
    shm_size: "2g"
    platform: linux/amd64


  chrome-node-5:
    image: selenium/node-chrome:4.10.0
    container_name: chrome-node-5
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
      - TZ=America/New_York
    shm_size: "2g"
    platform: linux/amd64


  chrome-node-6:
    image: selenium/node-chrome:4.10.0
    container_name: chrome-node-6
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
      - TZ=America/New_York
    shm_size: "2g"
    platform: linux/amd64

